/**
 * GENERATED by scripts/bake-hero.py in the same run as the grids in
 * public/portrait/. Do not edit it: change the bake and run it again.
 *
 * The screen is a 45-degree square lattice in log-polar space. Pixel (i, j)
 * of a grid is the lattice point A = a0 + 2i + (j & 1), B = b0 + j, at
 *   r = exp(u0 + k A),  th = v0 + k B,  (x, y) = (cx, cy) + r (cos th, sin th)
 * in design px (designW wide, 4:5), where the pitch is k * sqrt(2) * r.
 * `cols` and `rows` are the grid's own size, so a grid that does not belong
 * to these numbers is refused rather than drawn wrong.
 */
export type Lattice = {
  cols: number;
  rows: number;
  designW: number;
  dmax: number;
  cx: number;
  cy: number;
  k: number;
  u0: number;
  v0: number;
  a0: number;
  b0: number;
};

export const DESK: Lattice = {
  cols: 84,
  rows: 205,
  designW: 620,
  dmax: 1.5,
  cx: -568.722675,
  cy: 411.086957,
  k: 0.0037540083,
  u0: 6.6734420532,
  v0: 0,
  a0: -64,
  b0: -114,
};

export const SM: Lattice = {
  cols: 73,
  rows: 178,
  designW: 620,
  dmax: 1.5,
  cx: -568.722675,
  cy: 411.086957,
  k: 0.0043171096,
  u0: 6.6734420532,
  v0: 0,
  a0: -57,
  b0: -99,
};
