/** GENERATED by scripts/bake-portrait.py. Do not edit. */
/** Lit cells of the hero field (288 x 360, a 96 x 120 box at density 3). */
export const DOT_COUNT = 51747;
/** Cells per page-lattice step the fields were baked at. Must equal PORTRAIT_DENSITY in
 *  src/components/interactive/dot-board.tsx; scripts/check-density.mjs is the lock. */
export const PORTRAIT_FIELD_DENSITY = 3;
